server:
  port: 8001
  servlet:
    context-path: /backstate
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fitness?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 201310
  thymeleaf:
    prefix: classpath:/static/
    check-template-location: true
    cache: false
    suffix: .html
    encoding: UTF-8
    mode: HTML5
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.znsd.bean
logging.level.com.znsd.dao: debug


